config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  post "/graphql", to: "graphql#execute", defaults: { format: :json }
  get "/api/me.json", to: "api/credentials#me", defaults: {format: :json}
  get "/oauth/user", to: "api/credentials#oauth_user", defaults: {format: :json}

  resource :avatar, only: [:show]

  ActiveAdmin.routes(self)
  use_doorkeeper

  authenticate :user, lambda { |u| u.is_admin? } do
    namespace :admin do
      mount Sidekiq::Web => '/sidekiq'
    end

    namespace :api, defaults: {format: :json} do
      resources :discord_pairings, only: [:index, :show, :create]
    end
  end

  devise_for :users,
    controllers: { registrations: 'registrations' },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }

  get 'dashboard/workgroups', to: 'workgroups#dashboard'
  get 'rooms/print', to: 'rooms#print'
  get 'rooms/ratings', to: 'rooms#ratings'

  resources :timetables, only: [:show]
  resources :documents, only: [:show]

  authenticate :user do
    resources :terms, only: [:index] do
      member do
        get :select
      end
    end

    get 'rooms/print', to: 'rooms#print'
    get 'rooms/ratings', to: 'rooms#ratings'

    get 'workgroups/print', to: 'workgroups#print'
    resources :uploads

    resources :discord_pairings, only: [:destroy] do
      collection do
        get 'pair/:token', to: 'discord_pairings#pair', as: 'pair'
      end
    end
  end

  get '*path', to: 'web#index', via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails'
  }

  devise_scope :user do
    authenticated :user do
      root to: "web#index"
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  # mount ActionCable.server => '/cable'
end

app/models/upload.rb
# == Schema Information
#
# Table name: uploads
#
#  id         :uuid             not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  term_id    :uuid             not null
#
# Indexes
#
#  index_uploads_on_term_id  (term_id)
#
# Foreign Keys
#
#  fk_rails_...  (term_id => terms.id) ON DELETE => restrict
#
class Upload < ApplicationRecord
  belongs_to :term

  has_one_attached :file

  def file_name
    if file.attached?
      file.blob.filename
    end
  end

  def byte_size
    if file.attached?
      file.blob.byte_size
    end
  end

  def content_type
    if file.attached?
      file.blob.content_type
    end
  end
end

app/controllers/uploads_controller.rb
class UploadsController < WebController
  before_action :authorize_instructor!

  def index
    @upload = current_term.uploads.build
    @uploads = current_term.uploads
  end

  def create
    @upload = current_term.uploads.build(upload_params)

    if @upload.save
      redirect_to uploads_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @upload = current_term.uploads.find(params[:id])
    @upload.destroy

    redirect_to uploads_path, status: :see_other
  end

  private

  def upload_params
    params.require(:upload).permit(:file)
  end

end

app/views/uploads/_form.html.haml
= form_for @upload do |f|
  - if @upload.errors.any?
    #error_explanation
      %h2= "#{pluralize(@upload.errors.count, "error")} prohibited this upload from being saved:"
      %ul
        - @upload.errors.full_messages.each do |message|
          %li= message

  .mb-4
    = f.file_field :file, class: 'block w-full text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-primary-50 file:text-primary-700 hover:file:bg-primary-100'

  = f.submit 'Upload', class: 'button button-primary w-full'

app/views/uploads/index.html.haml
.container.mx-auto.my-8
  .box.max-w-sm.grow
    .px-6.py-4.border-b Uploads
    .px-6.pt-4
      = render 'form'

    .border.border-gray-300.border-t-0.relative.flex.items-center.justify-center.my-4

    .px-6
      - @uploads.reject(&:new_record?).map do |upload|
        .pb-4.flex.items-center
          .mr-4
            = file_type_icon upload.file
          .grow
            = link_to upload.file_name, rails_blob_path(upload.file, disposition: 'preview'), class: 'link', target: :_blank
            %p.text-sm.text-gray-600= number_to_human_size upload.byte_size
          .flex.gap-4
            = link_to rails_blob_path(upload.file, disposition: 'attachment') do
              = icon 'fa', 'download'
            = button_to upload_path(upload), method: :delete do
              = icon 'fa', 'trash-alt'